server:
  port: 8080

auth0:
  audience: https://dev-rkd-2v9z.us.auth0.com/api/v2/
  domain: dev-rkd-2v9z.us.auth0.com

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include:
          - beans
  endpoint:
    beans:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_management
    username: postgres
    password: Welcome
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: none
      show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/
