server:
  port: 8083

logging:
  level:
    root: 

management:
  endpoints:
    web:
      exposure:
        include:
          - beans
  endpoint:
    beans:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_management
    username: postgres
    password: Welcome
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    # hibernate:
    #   ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        sql-format: true
        ddl-auto: update
        generate-statistics: true

application:
  global-constants:
    group-max-size: 11

